# Generated by Django 4.1 on 2022-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
